-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.

drop database if exists projeto_bd;
create database projeto_bd;
USE projeto_bd;

CREATE TABLE Professor (
PNUSP INT PRIMARY KEY NOT NULL,
PNome VARCHAR(50) NOT NULL,
PDataIngresso DATE NOT NULL,
PDataSaida DATE NULL,
DepID INT NOT NULL
);

CREATE TABLE Topico (
TopID INT PRIMARY KEY AUTO_INCREMENT,
TNome VARCHAR(50) NOT NULL,
Resumo VARCHAR(500),
Bibliografia VARCHAR(500)
);

CREATE TABLE Aborda (
AboID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
TopID INT NOT NULL,
DisID INT NOT NULL,
FOREIGN KEY(TopID) REFERENCES Topico (TopID)
);

CREATE TABLE Estuda (
EstID INT PRIMARY KEY AUTO_INCREMENT,
Ano YEAR(4) NOT NULL,
Semestre INT NOT NULL,
Media FLOAT,
Situacao CHARACTER(1) NOT NULL,
PNUSP INT NOT NULL,
DisID INT NOT NULL,
ANUSP INT NOT NULL,
FOREIGN KEY(PNUSP) REFERENCES Professor (PNUSP)
);

CREATE TABLE Aluno (
ANUSP INT PRIMARY KEY NOT NULL,
Nome VARCHAR(50) NOT NULL
);

CREATE TABLE MatriculaEm (
MatID INT PRIMARY KEY AUTO_INCREMENT,
DataFimMatricula DATE,
DataMatricula DATE NOT NULL,
ANUSP INT NOT NULL,
CurID INT NOT NULL,
FOREIGN KEY(ANUSP) REFERENCES Aluno (ANUSP)
);

CREATE TABLE Disciplina (
DisID INT PRIMARY KEY AUTO_INCREMENT,
DisSigla VARCHAR(50) NOT NULL,
DisNome VARCHAR(50) NOT NULL,
MaxAlunos INT NOT NULL,
DisDescricao VARCHAR(500) NOT NULL,
DepID INT NOT NULL
);

CREATE TABLE EObrigatoria (
ObrID INT PRIMARY KEY AUTO_INCREMENT,
SemestreIdeal INT NOT NULL,
DisID INT NOT NULL,
CurID INT NOT NULL,
FOREIGN KEY(DisID) REFERENCES Disciplina (DisID)
);

CREATE TABLE Instituto (
InsID INT PRIMARY KEY AUTO_INCREMENT,
INome VARCHAR(50) NOT NULL,
ISigla VARCHAR(50) NOT NULL,
Campus VARCHAR(50) NOT NULL,
Cidade VARCHAR(50) NOT NULL
);

CREATE TABLE Curso (
CurID INT PRIMARY KEY AUTO_INCREMENT,
CNome VARCHAR(50) NOT NULL,
CDescricao VARCHAR(500) NOT NULL,
TempoDuracao INT NOT NULL,
PNUSP INT NOT NULL,
DepID INT NOT NULL,
FOREIGN KEY(PNUSP) REFERENCES Professor (PNUSP)
);

CREATE TABLE Departamento (
DepID INT PRIMARY KEY AUTO_INCREMENT,
DepNome VARCHAR(50) NOT NULL,
DepSigla VARCHAR(50) NOT NULL,
IID INT NOT NULL,
FOREIGN KEY(IID) REFERENCES Instituto (InsID)
);

ALTER TABLE Professor ADD FOREIGN KEY(DepID) REFERENCES Departamento (DepID);
ALTER TABLE Aborda ADD FOREIGN KEY(DisID) REFERENCES Disciplina (DisID);
ALTER TABLE Estuda ADD FOREIGN KEY(DisID) REFERENCES Disciplina (DisID);
ALTER TABLE Estuda ADD FOREIGN KEY(ANUSP) REFERENCES Aluno (ANUSP);
ALTER TABLE MatriculaEm ADD FOREIGN KEY(CurID) REFERENCES Curso (CurID);
ALTER TABLE Disciplina ADD FOREIGN KEY(DepID) REFERENCES Departamento (DepID);
ALTER TABLE EObrigatoria ADD FOREIGN KEY(CurID) REFERENCES Curso (CurID);
ALTER TABLE Curso ADD FOREIGN KEY(DepID) REFERENCES Departamento (DepID);
