#!/bin/bash 
root="results"

mkdir $root 2> /dev/null
rm -f $cpath $fpath $f2cpath 

read -e -p "executavel do C: " cprog
while ! [ -a $cprog ]; do
    read -e -p "$cprog nao existe. Digite de novo: " cprog
done

read -e -p "executavel do Fortran: " fprog
while ! [ -a $fprog ]; do
    read -e -p "$fprog nao existe. Digite de novo: " fprog
done

read -e -p "executavel do f2c: " f2cprog
while ! [ -a $f2cprog ]; do
    read -e -p "$f2cprog nao existe. Digite de novo: " f2cprog
done

read -e -p "arquivo da matriz: " matfile
while ! [ -a $matfile ]; do
    read -e -p "$matfile nao existe. Digite de novo: " matfile
done

read -e -p "Numero de repeticoes: " nreps
re='^[0-9]+$'
while ! [[ $nreps =~ $re ]] ; do
    read -e -p "$nreps nao e um numero. Digite de novo: " nreps
done

x=$( echo $matfile | grep -o -E [0-9]+)
x=$((x*100))
cpath=$root/"c_"$x"_"
fpath=$root/"fortran_"$x"_"
f2cpath=$root/"f2c_"$x"_"

for i in $(seq 1 $nreps); do
    /usr/bin/time -a -o $cpath"col.txt" -f "%e %U %S" -- $cprog -q -c < $matfile > /dev/null
    /usr/bin/time -a -o $cpath"row.txt" -f "%e %U %S" -- $cprog -q -c < $matfile > /dev/null
    /usr/bin/time -a -o $fpath"col.txt" -f "%e %U %S" -- $fprog -q -c < $matfile > /dev/null
    /usr/bin/time -a -o $fpath"row.txt" -f "%e %U %S" -- $fprog -q -c < $matfile > /dev/null
    /usr/bin/time -a -o $f2cpath"col.txt" -f "%e %U %S" -- $f2cprog -q -c < $matfile > /dev/null
    /usr/bin/time -a -o $f2cpath"row.txt" -f "%e %U %S" -- $f2cprog -q -c < $matfile > /dev/null
done
